NOISSUE - additional test
mainflux/benchmark pull request #4
Opened 2020-05-18 16:12 UTC by mteodor

Signed-off-by: Mirko Teodorovic <mirko.teodorovic@gmail.com>

2020-06-05 11:06 UTC, drasko requested changes
This test needs documentation.

2020-06-05 16:23 UTC, drasko reviewed
@blokovi @dusanb94 we are missing reports for this one.

I would accept it for now, and then @blokovi can add benchmarks.

Opinions?

2020-06-25 10:31 UTC, drasko requested changes

2020-06-25 10:31 UTC, drasko commented on mzbench/scenarios/burnout.bdl
> +
Kill this white line

2020-06-25 13:12 UTC, dusanb94 commented on mzbench/README.md
> +Burnout test is similar to the `Fan-In` just that message rate function is `comb` not a constant. Test is intended to be run for a long period of time to detect possible resource problem in deploymen
Maybe we should switch the ratio to 2:8? 1:9 sounds like a lot of waiting and not enough load.

2020-06-25 13:41 UTC, blokovi requested changes

2020-06-25 13:41 UTC, blokovi commented on mzbench/scenarios/burnout.bdl
> +
Scenario must start with `#!benchDL`
```MZBench supports two languages: eDSL based on erlang terms (default) and benchDL, to let it know that you use second option you need to specify this at the very beginning```

2020-06-25 16:58 UTC, blokovi approved these changes

2020-06-25 17:20 UTC, drasko commented on mzbench/scenarios/burnout.bdl
> +
@blokovi is this OK now?

2020-06-25 17:21 UTC, drasko approved these changes
LGTM

2020-06-25 17:21 UTC, merged